<?php
/**
 * Generated by the VALUNXT Capital admin panel — do not edit by hand.
 * Rewritten automatically whenever page SEO settings change.
 * Last written: 2026-08-05 05:52:50
 */
return array (
  '' => 
  array (
    'title' => 'Real Estate Wealth, Capital, Intelligence & Technology | VALUNXT Capital',
    'description' => 'VALUNXT Capital provides Real Estate Investment Advisory, capital solutions, market intelligence, and AI powered technology for investors, developers, institutions, and businesses across India and the UAE.',
    'canonical' => '',
    'robots' => 'index, follow',
    'keywords' => '',
    'og_title' => 'Real Estate Wealth, Capital, Intelligence & Technology | VALUNXT Capital',
    'og_description' => 'VALUNXT Capital provides Real Estate Investment Advisory, capital solutions, market intelligence, and AI powered technology for investors, developers, institutions, and businesses across India and the UAE.',
  ),
  'about' => 
  array (
    'title' => 'About | VALUNXT Capital',
    'description' => 'VALUNXT Capital is a premium real estate wealth, capital, intelligence, and technology group serving investors across India and the UAE.',
    'canonical' => '',
    'robots' => 'index, follow',
    'keywords' => '',
    'og_title' => 'About | VALUNXT Capital',
    'og_description' => 'VALUNXT Capital is a premium real estate wealth, capital, intelligence, and technology group serving investors across India and the UAE.',
  ),
  'about/careers' => 
  array (
    'title' => 'Careers | VALUNXT Capital',
    'description' => 'Explore areas of work at VALUNXT Capital, a real estate wealth, capital, research, and technology group operating across India and the UAE.',
    'canonical' => '',
    'robots' => 'index, follow',
    'keywords' => '',
    'og_title' => 'Careers | VALUNXT Capital',
    'og_description' => 'Explore areas of work at VALUNXT Capital, a real estate wealth, capital, research, and technology group operating across India and the UAE.',
  ),
  'blogs' => 
  array (
    'title' => 'Insights | VALUNXT Capital',
    'description' => 'Insights from VALUNXT Capital on real estate wealth, capital advisory, research, and technology across India and the UAE.',
    'canonical' => '',
    'robots' => 'index, follow',
    'keywords' => '',
    'og_title' => 'Insights | VALUNXT Capital',
    'og_description' => 'Insights from VALUNXT Capital on real estate wealth, capital advisory, research, and technology across India and the UAE.',
  ),
  'blogs/capital-planning-for-large-property-developments' => 
  array (
    'title' => 'Capital Planning for Large Property Developments | VALUNXT Capital',
    'description' => 'Large developments rarely fail for lack of a good idea; they fail for lack of a capital plan mapped across the full lifecycle.',
    'canonical' => '',
    'robots' => 'index, follow',
    'keywords' => '',
    'og_title' => 'Capital Planning for Large Property Developments | VALUNXT Capital',
    'og_description' => 'Large developments rarely fail for lack of a good idea; they fail for lack of a capital plan mapped across the full lifecycle.',
  ),
  'blogs/how-high-net-worth-investors-build-wealth-through-real-estate' => 
  array (
    'title' => 'How High-Net-Worth Investors Build Wealth Through Real Estate | VALUNXT Capital',
    'description' => 'For affluent investors, real estate is a disciplined, multi-decade strategy for compounding capital, generating income, and preserving wealth across cycles.',
    'canonical' => '',
    'robots' => 'index, follow',
    'keywords' => '',
    'og_title' => 'How High-Net-Worth Investors Build Wealth Through Real Estate | VALUNXT Capital',
    'og_description' => 'For affluent investors, real estate is a disciplined, multi-decade strategy for compounding capital, generating income, and preserving wealth across cycles.',
  ),
  'blogs/the-future-of-automated-valuation-models-avms' => 
  array (
    'title' => 'The Future of Automated Valuation Models (AVMs) | VALUNXT Capital',
    'description' => 'Automated valuation models are reshaping how quickly property can be valued; knowing their strengths and limits is essential.',
    'canonical' => '',
    'robots' => 'index, follow',
    'keywords' => '',
    'og_title' => 'The Future of Automated Valuation Models (AVMs) | VALUNXT Capital',
    'og_description' => 'Automated valuation models are reshaping how quickly property can be valued; knowing their strengths and limits is essential.',
  ),
  'blogs/why-market-intelligence-matters-before-every-property-investment' => 
  array (
    'title' => 'Why Market Intelligence Matters Before Every Property Investment | VALUNXT Capital',
    'description' => 'The best investment decisions are made before the deal, not during it; independent intelligence turns conviction into evidence.',
    'canonical' => '',
    'robots' => 'index, follow',
    'keywords' => '',
    'og_title' => 'Why Market Intelligence Matters Before Every Property Investment | VALUNXT Capital',
    'og_description' => 'The best investment decisions are made before the deal, not during it; independent intelligence turns conviction into evidence.',
  ),
  'clients' => 
  array (
    'title' => 'Clients | VALUNXT Capital',
    'description' => 'Discover the investors, family offices, NRIs, developers, and institutions VALUNXT Capital partners with across real estate advisory, capital solutions, research, and technology in India and the UAE.',
    'canonical' => '',
    'robots' => 'index, follow',
    'keywords' => '',
    'og_title' => 'Clients | VALUNXT Capital',
    'og_description' => 'Discover the investors, family offices, NRIs, developers, and institutions VALUNXT Capital partners with across real estate advisory, capital solutions, research, and technology in India and the UAE.',
  ),
  'community' => 
  array (
    'title' => 'Community | VALUNXT Capital',
    'description' => 'The VALUNXT Capital community.',
    'canonical' => '',
    'robots' => 'index, follow',
    'keywords' => '',
    'og_title' => 'Community | VALUNXT Capital',
    'og_description' => 'The VALUNXT Capital community.',
  ),
  'contact' => 
  array (
    'title' => 'Contact Us | VALUNXT Capital',
    'description' => 'Connect with the VALUNXT Capital advisory team in Dubai, Abu Dhabi, Mumbai, and Noida for real estate wealth, capital, research, and technology enquiries.',
    'canonical' => '',
    'robots' => 'index, follow',
    'keywords' => '',
    'og_title' => 'Contact Us | VALUNXT Capital',
    'og_description' => 'Connect with the VALUNXT Capital advisory team in Dubai, Abu Dhabi, Mumbai, and Noida for real estate wealth, capital, research, and technology enquiries.',
  ),
  'disclaimer' => 
  array (
    'title' => 'Disclaimer | VALUNXT Capital',
    'description' => 'Investment disclaimer for VALUNXT Capital. The information on valunxtcapital.com is for general informational purposes only and does not constitute investment advice.',
    'canonical' => '',
    'robots' => 'index, follow',
    'keywords' => '',
    'og_title' => 'Disclaimer | VALUNXT Capital',
    'og_description' => 'Investment disclaimer for VALUNXT Capital. The information on valunxtcapital.com is for general informational purposes only and does not constitute investment advice.',
  ),
  'faq' => 
  array (
    'title' => 'FAQ | VALUNXT Capital',
    'description' => 'Common questions about working with VALUNXT Capital — mandates, independent valuation, cross-border and NRI advisory, the group structure, and how we are paid.',
    'canonical' => '',
    'robots' => 'index, follow',
    'keywords' => '',
    'og_title' => 'FAQ | VALUNXT Capital',
    'og_description' => 'Common questions about working with VALUNXT Capital — mandates, independent valuation, cross-border and NRI advisory, the group structure, and how we are paid.',
  ),
  'free-consultation' => 
  array (
    'title' => 'Book a Consultation | VALUNXT Capital',
    'description' => 'Book a consultation with VALUNXT Capital to discuss real estate wealth, capital advisory, research, and technology across India and the UAE.',
    'canonical' => '',
    'robots' => 'index, follow',
    'keywords' => '',
    'og_title' => 'Book a Consultation | VALUNXT Capital',
    'og_description' => 'Book a consultation with VALUNXT Capital to discuss real estate wealth, capital advisory, research, and technology across India and the UAE.',
  ),
  'industries' => 
  array (
    'title' => 'Industries | VALUNXT Capital',
    'description' => 'Property sectors VALUNXT Capital covers — residential, office, retail, logistics, land and hospitality — and the client segments we act for across India and the UAE.',
    'canonical' => '',
    'robots' => 'index, follow',
    'keywords' => '',
    'og_title' => 'Industries | VALUNXT Capital',
    'og_description' => 'Property sectors VALUNXT Capital covers — residential, office, retail, logistics, land and hospitality — and the client segments we act for across India and the UAE.',
  ),
  'location' => 
  array (
    'title' => 'Location | VALUNXT Capital',
    'description' => 'Connect with VALUNXT Capital in Dubai, Abu Dhabi and across India. Find the office nearest to you and start a conversation with our advisory team.',
    'canonical' => '',
    'robots' => 'index, follow',
    'keywords' => '',
    'og_title' => 'Location | VALUNXT Capital',
    'og_description' => 'Connect with VALUNXT Capital in Dubai, Abu Dhabi and across India. Find the office nearest to you and start a conversation with our advisory team.',
  ),
  'network' => 
  array (
    'title' => 'Network | VALUNXT Capital',
    'description' => 'The relationships a VALUNXT engagement opens up — lending panels, investor community, accredited valuers and research — across India and the UAE.',
    'canonical' => '',
    'robots' => 'index, follow',
    'keywords' => '',
    'og_title' => 'Network | VALUNXT Capital',
    'og_description' => 'The relationships a VALUNXT engagement opens up — lending panels, investor community, accredited valuers and research — across India and the UAE.',
  ),
  'our-group' => 
  array (
    'title' => 'Our Group | VALUNXT Capital',
    'description' => 'The VALUNXT group of companies — VALUNXT Corporate Services, Reliant Surveyors, HouzzHunt, and HouzzHunt Mortgage.',
    'canonical' => '',
    'robots' => 'index, follow',
    'keywords' => '',
    'og_title' => 'Our Group | VALUNXT Capital',
    'og_description' => 'The VALUNXT group of companies — VALUNXT Corporate Services, Reliant Surveyors, HouzzHunt, and HouzzHunt Mortgage.',
  ),
  'our-group/houzzhunt' => 
  array (
    'title' => 'HouzzHunt | VALUNXT Capital',
    'description' => 'HouzzHunt — part of the VALUNXT group of companies.',
    'canonical' => '',
    'robots' => 'index, follow',
    'keywords' => '',
    'og_title' => 'HouzzHunt | VALUNXT Capital',
    'og_description' => 'HouzzHunt — part of the VALUNXT group of companies.',
  ),
  'our-group/houzzhunt-mortgage' => 
  array (
    'title' => 'HouzzHunt Mortgage | VALUNXT Capital',
    'description' => 'HouzzHunt Mortgage — part of the VALUNXT group of companies.',
    'canonical' => '',
    'robots' => 'index, follow',
    'keywords' => '',
    'og_title' => 'HouzzHunt Mortgage | VALUNXT Capital',
    'og_description' => 'HouzzHunt Mortgage — part of the VALUNXT group of companies.',
  ),
  'our-group/reliant-surveyors' => 
  array (
    'title' => 'Reliant Surveyors | VALUNXT Capital',
    'description' => 'Reliant Surveyors — part of the VALUNXT group of companies.',
    'canonical' => '',
    'robots' => 'index, follow',
    'keywords' => '',
    'og_title' => 'Reliant Surveyors | VALUNXT Capital',
    'og_description' => 'Reliant Surveyors — part of the VALUNXT group of companies.',
  ),
  'our-group/valunxt-corporate-services' => 
  array (
    'title' => 'VALUNXT Corporate Services | VALUNXT Capital',
    'description' => 'VALUNXT Corporate Services — part of the VALUNXT group of companies.',
    'canonical' => '',
    'robots' => 'index, follow',
    'keywords' => '',
    'og_title' => 'VALUNXT Corporate Services | VALUNXT Capital',
    'og_description' => 'VALUNXT Corporate Services — part of the VALUNXT group of companies.',
  ),
  'partnership' => 
  array (
    'title' => 'Partnership | VALUNXT Capital',
    'description' => '',
    'canonical' => '',
    'robots' => 'index, follow',
    'keywords' => '',
    'og_title' => 'Partnership | VALUNXT Capital',
    'og_description' => '',
  ),
  'privacy-policy' => 
  array (
    'title' => 'Privacy Policy | VALUNXT Capital',
    'description' => 'How VALUNXT Capital collects, uses, and protects the personal information of clients and visitors across our advisory services in India and the UAE.',
    'canonical' => '',
    'robots' => 'index, follow',
    'keywords' => '',
    'og_title' => 'Privacy Policy | VALUNXT Capital',
    'og_description' => 'How VALUNXT Capital collects, uses, and protects the personal information of clients and visitors across our advisory services in India and the UAE.',
  ),
  'research' => 
  array (
    'title' => 'Research & Reports | VALUNXT Capital',
    'description' => 'Independent research and market reports from VALUNXT Capital across India and the UAE real estate.',
    'canonical' => '',
    'robots' => 'index, follow',
    'keywords' => '',
    'og_title' => 'Research & Reports | VALUNXT Capital',
    'og_description' => 'Independent research and market reports from VALUNXT Capital across India and the UAE real estate.',
  ),
  'research/commercial-yields-capital-values' => 
  array (
    'title' => 'Commercial Yields & Capital Values | VALUNXT Capital',
    'description' => 'A data-led read on office, retail, and warehousing yields, rental growth, and capital values across key markets.',
    'canonical' => '',
    'robots' => 'index, follow',
    'keywords' => '',
    'og_title' => 'Commercial Yields & Capital Values | VALUNXT Capital',
    'og_description' => 'A data-led read on office, retail, and warehousing yields, rental growth, and capital values across key markets.',
  ),
  'research/dubai-residential-market-review' => 
  array (
    'title' => 'Dubai Residential Market Review | VALUNXT Capital',
    'description' => 'Supply, absorption, and pricing trends across Dubai\'s prime and mid-market residential communities.',
    'canonical' => '',
    'robots' => 'index, follow',
    'keywords' => '',
    'og_title' => 'Dubai Residential Market Review | VALUNXT Capital',
    'og_description' => 'Supply, absorption, and pricing trends across Dubai\'s prime and mid-market residential communities.',
  ),
  'research/india-real-estate-outlook-2026' => 
  array (
    'title' => 'India Real Estate Outlook 2026 | VALUNXT Capital',
    'description' => 'Where VALUNXT Capital sees value across India\'s residential and commercial real estate markets in 2026.',
    'canonical' => '',
    'robots' => 'index, follow',
    'keywords' => '',
    'og_title' => 'India Real Estate Outlook 2026 | VALUNXT Capital',
    'og_description' => 'Where VALUNXT Capital sees value across India\'s residential and commercial real estate markets in 2026.',
  ),
  'research/insights-2026' => 
  array (
    'title' => 'Insights 2026: View on Real Estate and Infrastructure | VALUNXT Capital',
    'description' => 'How Real Estate and Infrastructure are becoming increasingly attractive sources of resilient, inflation-protected returns as valuations stabilise and capital constraints persist.',
    'canonical' => '',
    'robots' => 'index, follow',
    'keywords' => '',
    'og_title' => 'Insights 2026: View on Real Estate and Infrastructure | VALUNXT Capital',
    'og_description' => 'How Real Estate and Infrastructure are becoming increasingly attractive sources of resilient, inflation-protected returns as valuations stabilise and capital constraints persist.',
  ),
  'research/nri-investment-trends' => 
  array (
    'title' => 'NRI Investment Trends | VALUNXT Capital',
    'description' => 'How Non-Resident Indians are allocating to real estate across India and the UAE — markets, ticket sizes, and structuring.',
    'canonical' => '',
    'robots' => 'index, follow',
    'keywords' => '',
    'og_title' => 'NRI Investment Trends | VALUNXT Capital',
    'og_description' => 'How Non-Resident Indians are allocating to real estate across India and the UAE — markets, ticket sizes, and structuring.',
  ),
  'services' => 
  array (
    'title' => 'Services | VALUNXT Capital',
    'description' => 'Explore VALUNXT Capital services across Real Estate Investment Advisory, Capital Advisory, Research & Intelligence, and Technology & AI in India and the UAE.',
    'canonical' => '',
    'robots' => 'index, follow',
    'keywords' => '',
    'og_title' => 'Services | VALUNXT Capital',
    'og_description' => 'Explore VALUNXT Capital services across Real Estate Investment Advisory, Capital Advisory, Research & Intelligence, and Technology & AI in India and the UAE.',
  ),
  'services/capital-advisory' => 
  array (
    'title' => 'Capital Advisory | VALUNXT Capital',
    'description' => 'Independent capital advisory from VALUNXT Capital — project funding, debt and equity structuring, and development finance across India and the UAE.',
    'canonical' => '',
    'robots' => 'index, follow',
    'keywords' => '',
    'og_title' => 'Capital Advisory | VALUNXT Capital',
    'og_description' => 'Independent capital advisory from VALUNXT Capital — project funding, debt and equity structuring, and development finance across India and the UAE.',
  ),
  'services/real-estate-investment-advisory' => 
  array (
    'title' => 'Real Estate Investment Advisory | VALUNXT Capital',
    'description' => 'Strategic Real Estate Investment Advisory for HNIs, NRIs, family offices, and institutions across India, the UAE, and international markets.',
    'canonical' => '',
    'robots' => 'index, follow',
    'keywords' => '',
    'og_title' => 'Real Estate Investment Advisory | VALUNXT Capital',
    'og_description' => 'Strategic Real Estate Investment Advisory for HNIs, NRIs, family offices, and institutions across India, the UAE, and international markets.',
  ),
  'services/research-intelligence' => 
  array (
    'title' => 'Research & Intelligence | VALUNXT Capital',
    'description' => 'Independent research, valuation intelligence, and market analysis from VALUNXT Capital to strengthen investment decisions across India and the UAE.',
    'canonical' => '',
    'robots' => 'index, follow',
    'keywords' => '',
    'og_title' => 'Research & Intelligence | VALUNXT Capital',
    'og_description' => 'Independent research, valuation intelligence, and market analysis from VALUNXT Capital to strengthen investment decisions across India and the UAE.',
  ),
  'services/technology-ai' => 
  array (
    'title' => 'Technology & AI | VALUNXT Capital',
    'description' => 'AI powered platforms, analytics, and enterprise technology built for real estate and investment intelligence across India and the UAE.',
    'canonical' => '',
    'robots' => 'index, follow',
    'keywords' => '',
    'og_title' => 'Technology & AI | VALUNXT Capital',
    'og_description' => 'AI powered platforms, analytics, and enterprise technology built for real estate and investment intelligence across India and the UAE.',
  ),
  'services/technology-ai/platform' => 
  array (
    'title' => 'VALUNXT Intelligence Platform | VALUNXT Capital',
    'description' => 'The valuation, market analytics, portfolio and workflow modules behind our Technology & AI practice — what each one takes in, what it produces, and where it stops.',
    'canonical' => '',
    'robots' => 'index, follow',
    'keywords' => '',
    'og_title' => 'VALUNXT Intelligence Platform | VALUNXT Capital',
    'og_description' => 'The valuation, market analytics, portfolio and workflow modules behind our Technology & AI practice — what each one takes in, what it produces, and where it stops.',
  ),
  'terms-conditions' => 
  array (
    'title' => 'Terms & Conditions | VALUNXT Capital',
    'description' => 'Terms and Conditions for the VALUNXT Capital website, a real estate wealth, capital, intelligence, and technology group across India and the UAE.',
    'canonical' => '',
    'robots' => 'index, follow',
    'keywords' => '',
    'og_title' => 'Terms & Conditions | VALUNXT Capital',
    'og_description' => 'Terms and Conditions for the VALUNXT Capital website, a real estate wealth, capital, intelligence, and technology group across India and the UAE.',
  ),
);
